[project]
name = "training2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "reportlab>=4.4.7",
    "windows-curses>=2.4.1; platform_system == \"Windows\"",
]
